name: Build Benchmarks on Ubuntu
on: [push]
jobs:
  BuildBenchmarks:
    # Only Ubuntu for now.
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: sudo apt update && sudo apt -qq --assume-yes full-upgrade && sudo apt install -qq -y build-essential crossbuild-essential-arm64 gcc-riscv64-linux-gnu ocl-icd-opencl-dev opencl-headers libnuma-dev b3sum unzip
      - name: Wild tomfoolery attempt
        run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && brew install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build all benchmarks
        run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && make ci
      - name: Package benchmarks
        run: make package
      - name: b3sum
        run: b3sum clammarks.txz
#      - name: Upload package
#        env:
#          UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
#          UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
#        run:  curl -X PUT -T clammarks.txz -H "$UPLOAD_KEY" "$UPLOAD_URL"
